### ISSUE TITLE
Trajectory Plot and Error plot

### ISSUE THREAD

**Issue by shivamgarg1901** [Jaeyoung-Lim/mavros_controllers#78]
Hi! Jaeyoung-Lim 
I was trying to plot the Trajectory using rqt_plot but it is not taking the message mavros/PoseMessage/pose. Please help me out with same.
Also, can you tell me how could I plot the deviation of actual trajectory from the desired trajectory?

**Comment by Jaeyoung-Lim** [comment]
@shivamgarg1901 Could you explain more on what is not working with rviz?

On the deviation of the actual trajectory to the desired trajectory, is not being visualized yet. I will try to implement this when I have time. 

I am also trying to measure the statistics of the error the controller has in order to measure the performance of each controller on #77 

Hope this helps

**Comment by Jaeyoung-Lim** [comment]
@shivamgarg1901 Actually, it wasn't too hard to implement it so I made a PR on #79 

Please feel free to test it out

**Comment by shivamgarg1901** [comment]
Hi! 
Thanks for your reply. I tried to run the updated repository.It is running everything except it is not showing any drone in the gazebo environment and not showing any trajectory in Rviz. Here is the screenshot of the error it is showing.
![file](https://user-images.githubusercontent.com/25364311/56422727-938c4180-62c6-11e9-812a-2aeb14df7013.png)
Please help me out with the same.
